### ISSUE TITLE
Old examples from readme 

### ISSUE THREAD

**Issue by Adamko23** [maxpowel/rs-crypto-com-exchange#2]
Hi, 
I found your library at crates.io and I want to try your library, but the example from read.me is works only on older versions. But I see new version is different. Can you change it please? :)

**Comment by maxpowel** [comment]
Sure, I forgot that. I'm updating them right

**Comment by maxpowel** [comment]
I added a simple example here https://github.com/maxpowel/rs-crypto-com-exchange/tree/master/examples/crypto_log

I will provide more documentation but with this example you can at least see how does it work. It just listen for trades but adding the functionality for other messages (candlestick, book...) is very similar.

Anyway, if you have any question or whatever please tell me.
